version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-server
    environment:
      MYSQL_ROOT_PASSWORD: SecPwd123
      MYSQL_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: SecPwd123
    volumes:
      - /opt/shared/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - kong-net
    command:
      --log-bin=mysql-bin
      --log-bin-trust-function-creators=true
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --bind-address=0.0.0.0

networks:
  kong-net:
    driver: bridge